#!/bin/sh

if [ -f "/etc/default/pystatd" ]; then
	mv /etc/default/pystatd /etc/default/pystatsd
fi

if [ -f "/etc/init/pystatd.conf" ]; then
	stop pystatd || true
	cp /usr/share/doc/python-statsd/pystatsd.conf.upstart /etc/init/pystatsd.conf
	start pystatsd || true
fi

if [ -f "/etc/init.d/pystatsd" ]; then
	/etc/init.d/pystatsd stop || true
	cp /usr/share/doc/python-statsd/pystatsd.init.debian /etc/init.d/pystatsd
	/etc/init.d/pystatsd start || true
fi

#DEBHELPER#
